### ISSUE TITLE
website: make table of content sidebar visually clear

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm-docs#189]
Originally posted in the OSM repo by @mudit-01:
In the docs website https://docs.openservicemesh.io/ the sidebar as some space issue in alignment.

![image](https://user-images.githubusercontent.com/21697719/134532364-cdcec913-4d15-4b62-9778-253d896001cb.png)

**Comment by allenlsy** [comment]
This is resolved with new theme.

**Comment by shashankram** [comment]
This is still not resolved. As you can see below, the hierarchy of topics is still confusing:
![image](https://user-images.githubusercontent.com/21697719/174685882-8fc30a50-addb-4c5d-a98d-a6c4ac646dd9.png)

**Comment by allenlsy** [comment]
Agree. The new theme only resolves the spacing issue.
